name: Daily Task

on:
  schedule:
    - cron:  '0 8-20/4 * * *' # 每4小时运行一次
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' # 您可以选择需要的 Node.js 版本

      - name: Install dependencies
        run: npm i

      - name: Run daily-task.sh
        run: node src/main.js

      - name: Commit and push if it changed
        run: |
          git diff
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Action"
          git add .
          git commit -am "Automated snapshot" || exit 0
          git push
